export const locations = [
    {
        title: 'Sydney',
        items: [
            { title: 'Newtown', slug: 'newtown' },
            { title: 'Redfern', slug: 'redfern' },
            { title: 'Surry Hills', slug: 'surry-hills' },
            { title: 'Ultimo', slug: 'ultimo' },
            { title: 'Alexandria', slug: 'alexandria' },
            { title: 'Waterloo', slug: 'waterloo' },
            { title: 'Petersham', slug: 'petersham' },
            { title: 'Summer Hill', slug: 'summer-hill' },
            { title: 'Dulwich Hill', slug: 'dulwich-hill' },
            { title: 'Leichhardt', slug: 'leichhardt' },
            { title: 'Annandale', slug: 'annandale' },
            { title: 'Glebe', slug: 'glebe' },
            { title: 'Eveleigh', slug: 'eveleigh' },
            { title: 'Rosebery', slug: 'rosebery' },
            { title: 'Ashfield', slug: 'ashfield' },
            { title: 'Croydon', slug: 'croydon' },
            { title: 'Zetland', slug: 'zetland' },
            { title: 'Mascot', slug: 'mascot' },
            { title: 'Kensington', slug: 'kensington' },
            { title: 'Darlinghurst', slug: 'darlinghurst' },
            { title: 'Marrickville', slug: 'marrickville' },
            { title: 'Potts Point', slug: 'potts-point' },
            { title: 'Bondi Junction', slug: 'bondi-junction' },
            { title: 'Coogee', slug: 'coogee' },
            { title: 'South Coogee', slug: 'south-coogee' },
            { title: 'Bondi', slug: 'bondi' },
            { title: 'Malabar', slug: 'malabar' },
            { title: 'Bronte', slug: 'bronte' },
            { title: 'Clovelly', slug: 'clovelly' },
            { title: 'Waverley', slug: 'waverley' },
            { title: 'Randwick', slug: 'randwick' },
            { title: 'Kingsford', slug: 'kingsford' },
            { title: 'Rose Bay', slug: 'rose-bay' },
            { title: 'Double Bay', slug: 'double-bay' },
            { title: 'Maroubra', slug: 'maroubra' },
            { title: 'Chifley', slug: 'chifley' },
            { title: 'Ramsgate', slug: 'ramsgate' },
            { title: 'Rockdale', slug: 'rockdale' },
            { title: 'Chatswood', slug: 'chatswood' },
            { title: 'Neutral Bay', slug: 'neutral-bay' },
            { title: 'North Sydney', slug: 'north-sydney' },
            { title: 'Cremorne', slug: 'cremorne' },
            { title: 'Crows Nest', slug: 'crows-nest' },
            { title: 'St Leonards', slug: 'st-leonards' },
            { title: 'Mosman', slug: 'mosman' },
            { title: 'Parramatta', slug: 'parramatta' },
            { title: 'North Ryde', slug: 'north-ryde' },
            { title: 'Eastwood', slug: 'eastwood' },
            { title: 'Lindfield', slug: 'lindfield' },
            { title: 'Manly', slug: 'manly' },
            { title: 'Balgowlah', slug: 'balgowlah' },
            { title: 'Seaforth', slug: 'seaforth' },
            { title: 'Willoughby', slug: 'willoughby' },
            { title: 'Willoughby East', slug: 'willoughby-east' },
            { title: 'North Willoughby', slug: 'north-willoughby' },
            { title: 'Northbridge', slug: 'northbridge' },
            { title: 'Roseville', slug: 'roseville' },
            { title: 'Roseville Chase', slug: 'roseville-chase' },
            { title: 'Rhodes', slug: 'rhodes' },
            { title: 'Woolloomooloo', slug: 'woolloomooloo' },
            { title: 'Macquarie Park', slug: 'macquarie-park' },
            { title: 'Carlingford', slug: 'carlingford' },
            { title: 'Castle Hill', slug: 'castle-hill' },
            { title: 'Seven Hills', slug: 'seven-hills' },
            { title: 'Baulkham Hills', slug: 'baulkham-hills' },
            { title: 'Blacktown', slug: 'blacktown' },
            { title: 'Campbelltown', slug: 'campbelltown' },
            { title: 'Vaucluse', slug: 'vaucluse' },
            { title: 'Epping', slug: 'epping' },
            { title: 'Ryde', slug: 'ryde' },
        ],
    },
    {
        title: 'Melbourne',
        meta: {},
        items: [
            { title: 'Abbotsford', slug: 'abbotsford' },
            { title: 'Aberfeldie', slug: 'aberfeldie' },
            { title: 'Airport West', slug: 'airport-west' },
            { title: 'Ascot Vale', slug: 'ascot-vale' },
            { title: 'Ashburton', slug: 'ashburton' },
            { title: 'Ashwood', slug: 'ashwood' },
            { title: 'Aspendale', slug: 'aspendale' },
            { title: 'Avondale Heights', slug: 'avondale-heights' },
            { title: 'Balaclava', slug: 'balaclava' },
            { title: 'Balwyn', slug: 'balwyn' },
            { title: 'Bayswater', slug: 'bayswater' },
            { title: 'Beaconsfield', slug: 'beaconsfield' },
            { title: 'Beaumaris', slug: 'beaumaris' },
            { title: 'Bellfield', slug: 'bellfield' },
            { title: 'Bentleigh', slug: 'bentleigh' },
            { title: 'Blackburn', slug: 'blackburn' },
            { title: 'Black Rock', slug: 'black-rock' },
            { title: 'Box Hill', slug: 'box-hill' },
            { title: 'Brighton', slug: 'brighton' },
            { title: 'Clifton Hill', slug: 'clifton-hill' },
            { title: 'Coburg', slug: 'coburg' },
            { title: 'Collingwood', slug: 'collingwood' },
            { title: 'Craigieburn', slug: 'craigieburn' },
            { title: 'Cranbourne', slug: 'cranbourne' },
            { title: 'Cremorne', slug: 'cremorne' },
            { title: 'Croydon', slug: 'croydon' },
            { title: 'Dandenong', slug: 'dandenong' },
            { title: 'Diamond Creek', slug: 'diamond-creek' },
            { title: 'Doncaster', slug: 'doncaster' },
            { title: 'Eaglemont', slug: 'eaglemont' },
            { title: 'East Melbourne', slug: 'east-melbourne' },
            { title: 'Elsternwick', slug: 'elsternwick' },
            { title: 'Eltham', slug: 'eltham' },
            { title: 'Elwood', slug: 'elwood' },
        ],
    },
];

export const cities = ['Sydney', 'Melbourne'];
