export const cities = [
    {
        title: 'Sydney',
        items: [
            { title: 'Newtown', slug: 'newtown' },
            { title: 'Redfern', slug: 'redfern' },
            { title: 'Surry Hills', slug: 'surry-hills' },
            { title: 'Ultimo', slug: 'ultimo' },
            { title: 'Alexandria', slug: 'alexandria' },
            { title: 'Waterloo', slug: 'waterloo' },
            { title: 'Petersham', slug: 'petersham' },
            { title: 'Summer Hill', slug: 'summer-hill' },
            { title: 'Dulwich Hill', slug: 'dulwich-hill' },
            { title: 'Leichhardt', slug: 'leichhardt' },
            { title: 'Annandale', slug: 'annandale' },
            { title: 'Glebe', slug: 'glebe' },
            { title: 'Eveleigh', slug: 'eveleigh' },
            { title: 'Rosebery', slug: 'rosebery' },
            { title: 'Ashfield', slug: 'ashfield' },
            { title: 'Croydon', slug: 'croydon' },
            { title: 'Zetland', slug: 'zetland' },
            { title: 'Mascot', slug: 'mascot' },
            { title: 'Kensington', slug: 'kensington' },
            { title: 'Darlinghurst', slug: 'darlinghurst' },
            { title: 'Marrickville', slug: 'marrickville' },
            { title: 'Potts Point', slug: 'potts-point' },
            { title: 'Bondi Junction', slug: 'bondi-junction' },
            { title: 'Coogee', slug: 'coogee' },
            { title: 'South Coogee', slug: 'south-coogee' },
            { title: 'Bondi', slug: 'bondi' },
            { title: 'Malabar', slug: 'malabar' },
            { title: 'Bronte', slug: 'bronte' },
            { title: 'Clovelly', slug: 'clovelly' },
            { title: 'Waverley', slug: 'waverley' },
            { title: 'Randwick', slug: 'randwick' },
            { title: 'Kingsford', slug: 'kingsford' },
            { title: 'Rose Bay', slug: 'rose-bay' },
            { title: 'Double Bay', slug: 'double-bay' },
            { title: 'Maroubra', slug: 'maroubra' },
            { title: 'Chifley', slug: 'chifley' },
            { title: 'Ramsgate', slug: 'ramsgate' },
            { title: 'Rockdale', slug: 'rockdale' },
            { title: 'Chatswood', slug: 'chatswood' },
            { title: 'Neutral Bay', slug: 'neutral-bay' },
            { title: 'North Sydney', slug: 'north-sydney' },
            { title: 'Cremorne', slug: 'cremorne' },
            { title: 'Crows Nest', slug: 'crows-nest' },
            { title: 'St Leonards', slug: 'st-leonards' },
            { title: 'Mosman', slug: 'mosman' },
            { title: 'Parramatta', slug: 'parramatta' },
            { title: 'North Ryde', slug: 'north-ryde' },
            { title: 'Eastwood', slug: 'eastwood' },
            { title: 'Lindfield', slug: 'lindfield' },
            { title: 'Manly', slug: 'manly' },
            { title: 'Balgowlah', slug: 'balgowlah' },
            { title: 'Seaforth', slug: 'seaforth' },
            { title: 'Willoughby', slug: 'willoughby' },
            { title: 'Willoughby East', slug: 'willoughby-east' },
            { title: 'North Willoughby', slug: 'north-willoughby' },
            { title: 'Northbridge', slug: 'northbridge' },
            { title: 'Roseville', slug: 'roseville' },
            { title: 'Roseville Chase', slug: 'roseville-chase' },
            { title: 'Rhodes', slug: 'rhodes' },
            { title: 'Woolloomooloo', slug: 'woolloomooloo' },
            { title: 'Macquarie Park', slug: 'macquarie-park' },
            { title: 'Carlingford', slug: 'carlingford' },
            { title: 'Castle Hill', slug: 'castle-hill' },
            { title: 'Seven Hills', slug: 'seven-hills' },
            { title: 'Baulkham Hills', slug: 'baulkham-hills' },
            { title: 'Blacktown', slug: 'blacktown' },
            { title: 'Campbelltown', slug: 'campbelltown' },
            { title: 'Vaucluse', slug: 'vaucluse' },
            { title: 'Epping', slug: 'epping' },
            { title: 'Ryde', slug: 'ryde' },
        ],
    },
    {
        title: 'Melbourne',
        meta: {},
        items: [
            { title: 'Abbotsford', slug: 'abbotsford' },
            { title: 'Aberfeldie', slug: 'aberfeldie' },
            { title: 'Airport West', slug: 'airport-west' },
            { title: 'Ascot Vale', slug: 'ascot-vale' },
            { title: 'Ashburton', slug: 'ashburton' },
            { title: 'Ashwood', slug: 'ashwood' },
            { title: 'Aspendale', slug: 'aspendale' },
            { title: 'Avondale Heights', slug: 'avondale-heights' },
            { title: 'Balaclava', slug: 'balaclava' },
            { title: 'Balwyn', slug: 'balwyn' },
            { title: 'Bayswater', slug: 'bayswater' },
            { title: 'Beaconsfield', slug: 'beaconsfield' },
            { title: 'Beaumaris', slug: 'beaumaris' },
            { title: 'Bellfield', slug: 'bellfield' },
            { title: 'Bentleigh', slug: 'bentleigh' },
            { title: 'Blackburn', slug: 'blackburn' },
            { title: 'Black Rock', slug: 'black-rock' },
            { title: 'Box Hill', slug: 'box-hill' },
            { title: 'Brighton', slug: 'brighton' },
            { title: 'Clifton Hill', slug: 'clifton-hill' },
            { title: 'Coburg', slug: 'coburg' },
            { title: 'Collingwood', slug: 'collingwood' },
            { title: 'Craigieburn', slug: 'craigieburn' },
            { title: 'Cranbourne', slug: 'cranbourne' },
            { title: 'Cremorne', slug: 'cremorne' },
            { title: 'Croydon', slug: 'croydon' },
            { title: 'Dandenong', slug: 'dandenong' },
            { title: 'Diamond Creek', slug: 'diamond-creek' },
            { title: 'Doncaster', slug: 'doncaster' },
            { title: 'Eaglemont', slug: 'eaglemont' },
            { title: 'East Melbourne', slug: 'east-melbourne' },
            { title: 'Elsternwick', slug: 'elsternwick' },
            { title: 'Eltham', slug: 'eltham' },
            { title: 'Elwood', slug: 'elwood' },
        ],
    },
];

export const locations = [
    {
        title: 'Sydney',
        meta: {},
        items: [
            { title: 'Newtown', href: '/sydney/newtown' },
            { title: 'Redfern', href: '/sydney/redfern' },
            { title: 'Surry Hills', href: '/sydney/surry-hills' },
            { title: 'Ultimo', href: '/sydney/ultimo' },
            { title: 'Alexandria', href: '/sydney/alexandria' },
            { title: 'Waterloo', href: '/sydney/waterloo' },
            { title: 'Petersham', href: '/sydney/petersham' },
            { title: 'Summer Hill', href: '/sydney/summer-hill' },
            { title: 'Dulwich Hill', href: '/sydney/dulwich-hill' },
            { title: 'Leichhardt', href: '/sydney/leichhardt' },
            { title: 'Annandale', href: '/sydney/annandale' },
            { title: 'Glebe', href: '/sydney/glebe' },
            { title: 'Eveleigh', href: '/sydney/eveleigh' },
            { title: 'Rosebery', href: '/sydney/rosebery' },
            { title: 'Ashfield', href: '/sydney/ashfield' },
            { title: 'Zetland', href: '/sydney/zetland' },
            { title: 'Mascot', href: '/sydney/mascot' },
            { title: 'Kensington', href: '/sydney/kensington' },
            { title: 'Darlinghurst', href: '/sydney/darlinghurst' },
            { title: 'Marrickville', href: '/sydney/marrickville' },
            { title: 'Potts Point', href: '/sydney/potts-point' },
            { title: 'Bondi Junction', href: '/sydney/bondi-junction' },
            { title: 'Coogee', href: '/sydney/coogee' },
            { title: 'South Coogee', href: '/sydney/south-coogee' },
            { title: 'Bondi', href: '/sydney/bondi' },
            { title: 'Little Bay', href: '/sydney/little-bay' },
            { title: 'Malabar', href: '/sydney/malabar' },
            { title: 'Bronte', href: '/sydney/bronte' },
            { title: 'Clovelly', href: '/sydney/clovelly' },
            { title: 'Waverley', href: '/sydney/waverley' },
            { title: 'Randwick', href: '/sydney/randwick' },
            { title: 'Kingsford', href: '/sydney/kingsford' },
            { title: 'Rose Bay', href: '/sydney/rose-bay' },
            { title: 'Double Bay', href: '/sydney/double-bay' },
            { title: 'Maroubra', href: '/sydney/maroubra' },
            { title: 'Chifley', href: '/sydney/chifley' },
            { title: 'Ramsgate', href: '/sydney/ramsgate' },
            { title: 'Rockdale', href: '/sydney/rockdale' },
            { title: 'Chatswood', href: '/sydney/chatswood' },
            { title: 'Neutral Bay', href: '/sydney/neutral-bay' },
            { title: 'North Sydney', href: '/sydney/north-sydney' },
            { title: 'Cremorne', href: '/sydney/cremorne' },
            { title: 'Crows Nest', href: '/sydney/crows-nest' },
            { title: 'St Leonards', href: '/sydney/st-leonards' },
            { title: 'Mosman', href: '/sydney/mosman' },
            { title: 'Parramatta', href: '/sydney/parramatta' },
            { title: 'North Ryde', href: '/sydney/north-ryde' },
            { title: 'Eastwood', href: '/sydney/eastwood' },
            { title: 'Lindfield', href: '/sydney/lindfield' },
            { title: 'Manly', href: '/sydney/manly' },
            { title: 'Balgowlah', href: '/sydney/balgowlah' },
            { title: 'Seaforth', href: '/sydney/seaforth' },
            { title: 'Willoughby', href: '/sydney/willoughby' },
            { title: 'Northbridge', href: '/sydney/northbridge' },
            { title: 'Roseville', href: '/sydney/roseville' },
            { title: 'Rhodes', href: '/sydney/rhodes' },
            { title: 'Woolloomooloo', href: '/sydney/woolloomooloo' },
            { title: 'Macquarie Park', href: '/sydney/macquarie-park' },
            { title: 'Carlingford', href: '/sydney/carlingford' },
            { title: 'Castle Hill', href: '/sydney/castle-hill' },
            { title: 'Seven Hills', href: '/sydney/seven-hills' },
            { title: 'Blacktown', href: '/sydney/blacktown' },
            { title: 'Campbelltown', href: '/sydney/campbelltown' },
            { title: 'Paddington', href: '/sydney/paddington' },
            { title: 'Elizabeth Bay', href: '/sydney/elizabeth-bay' },
            { title: 'Haymarket', href: '/sydney/haymarket' },
            { title: 'Camperdown', href: '/sydney/camperdown' },
            { title: 'Stanmore', href: '/sydney/Stanmore' },
            { title: 'Five Dock', href: '/sydney/five-dock' },
            { title: 'Haberfield', href: '/sydney/haberfield' },
            { title: 'Lilyfield', href: '/sydney/lilyfield' },
            { title: 'Rozelle', href: '/sydney/rozelle' },
            { title: 'Balmain', href: '/sydney/balmain' },
            { title: 'Birchgrove', href: '/sydney/birchgrove' },
            { title: 'Balmain East', href: '/sydney/balmain-east' },
            { title: 'Covelly', href: '/sydney/covelly' },
            { title: 'Tamarama', href: '/sydney/tamarama' },
            { title: 'Queens Park', href: '/sydney/queens-park' },
            { title: 'North Bordi', href: '/sydney/north-bondi' },
            { title: 'Rose Bay', href: '/sydney/rose-bay' },
            { title: 'Vaucluse', href: '/sydney/vaucluse' },
            { title: 'Eastlakes', href: '/sydney/eastlakes' },
            { title: 'Pagewood', href: '/sydney/pagewood' },
            { title: 'Batony', href: '/sydney/botany' },
            { title: 'Hillsdale', href: '/sydney/hillsdale' },
            { title: 'Matraville', href: '/sydney/matraville' },
            { title: 'Chifley', href: '/sydney/chifley' },
            { title: 'Malabar', href: '/sydney/malabar' },
            { title: 'Beaconsfield', href: '/sydney/beaconsfield' },
            { title: 'Tempe', href: '/sydney/tempe' },
            { title: 'Wolli Creek', href: '/sydney/wolli-creek' },
            { title: 'Turrella', href: '/sydney/turrella' },
            { title: 'Kyeemagh', href: '/sydney/kyeemagh' },
            { title: 'Banksia', href: '/sydney/banksia' },
            { title: 'Ramsgate', href: '/sydney/ramsgate' },
            { title: 'Sans Souci', href: '/sydney/sans-souci' },
            { title: 'Sandringham', href: '/sydney/sandringham' },
            { title: 'Cronulla', href: '/sydney/cronulla' },
            { title: 'Woolooware', href: '/sydney/woolooware' },
            { title: 'Burraneer', href: '/sydney/burraneer' },
            { title: 'Caringbah', href: '/sydney/caringbah' },
            { title: 'South Caringbah', href: '/sydney/south-caringbah' },
            { title: 'Taren Point', href: '/sydney/taren-point' },
            { title: 'Miranda', href: '/sydney/miranda' },
            { title: 'Yowie Bay', href: '/sydney/yowie-bay' },
            { title: 'Gymea Bay', href: '/sydney/gymea-bay' },
            { title: 'Gymea', href: '/sydney/gymea' },
            { title: 'Grays Point', href: '/sydney/grays-point' },
            { title: 'Sutherland', href: '/sydney/sutherland' },
            { title: 'Kirrawee', href: '/sydney/kirrawee' },
            { title: 'Kangaroo Point', href: '/sydney/kangaroo-point' },
            { title: 'Kareela', href: '/sydney/kareela' },
            { title: 'Oyster Bay', href: '/sydney/oyster-bay' },
            { title: 'Como', href: '/sydney/como' },
            { title: 'Bonnet Bay', href: '/sydney/bonnet-bay' },
            { title: 'Oately', href: '/sydney/oately' },
            { title: 'Kyle Bay', href: '/sydney/kyle-bay' },
            { title: 'Blakehurst', href: '/sydney/blakehurst' },
            { title: 'Monterey', href: '/sydney/monterey' },
            { title: 'Kogarah', href: '/sydney/kogarah' },
            { title: 'Arncliffe', href: '/sydney/arncliffe' },
            { title: 'Bexley', href: '/sydney/bexley' },
            { title: 'Bexley North', href: '/sydney/bexley-north' },
            { title: 'Turrella', href: '/sydney/turrella' },
            { title: 'Bardwell Valley', href: '/sydney/bardwell-valley' },
            { title: 'Bardwell Park', href: '/sydney/bardwell-park' },
            { title: 'Bardwell Park', href: '/sydney/bardwell-park' },
            { title: 'Earlwood', href: '/sydney/earlwood' },
            { title: 'Kingsgrove', href: '/sydney/kingsgrove' },
            { title: 'Clemton Park', href: '/sydney/clemton-park' },
            { title: 'Roselands', href: '/sydney/roselands' },
            { title: 'Canterbury', href: '/sydney/canterbury' },
            { title: 'Riverwood', href: '/sydney/riverwood' },
            { title: 'Peakhurst', href: '/sydney/peakhurst' },
            { title: 'Mortdale', href: '/sydney/mortdale' },
            { title: 'Lagarno', href: '/sydney/lugarno' },
            { title: 'Padstow-heights', href: '/sydney/padstow-heights' },
            { title: 'Padstow', href: '/sydney/padstow' },
            { title: 'Revesby', href: '/sydney/revesby' },
            { title: 'Panania', href: '/sydney/Panania' },
            { title: 'Picnic Point', href: '/sydney/picnic-point' },
            { title: 'Milperra', href: '/sydney/milperra' },
            { title: 'Voyger Point', href: '/sydney/voyger-point' },
            { title: 'Holsworthy', href: '/sydney/holsworthy' },
            { title: 'Hammondville', href: '/sydney/hammondville' },
            { title: 'Wattle Grove', href: '/sydney/wattle-grove' },
            { title: 'Moorebank', href: '/sydney/moorebank' },
            { title: 'Liverpool', href: '/sydney/liverpool' },
            { title: 'Casula', href: '/sydney/casula' },
            { title: 'Glenfield', href: '/sydney/glenfield' },
            { title: 'Macquarie Fields', href: '/sydney/macquarie-fields' },
            { title: 'Ingleburn', href: '/sydney/ingleburn' },
            { title: 'Minto', href: '/sydney/minto' },
            { title: 'Ruse', href: '/sydney/ruse' },
            { title: 'Airds', href: '/sydney/airds' },
            { title: 'Bradbury', href: '/sydney/bradbury' },
            { title: 'St Helens Park', href: '/sydney/st-helens-park' },
            { title: 'Rosemeadow', href: '/sydney/rosemeadow' },
            { title: 'Ambarvale', href: '/sydney/ambarvale' },
            { title: 'Glen Alpine', href: '/sydney/glen-alpine' },
            { title: 'Englorie Park', href: '/sydney/englorie-park' },
            { title: 'Blair Athol', href: '/sydney/blair-athol' },
            { title: 'Beumeah', href: '/sydney/beumeah' },
            { title: 'Woodbine', href: '/sydney/woodbine' },
            { title: 'Blairmount', href: '/sydney/blairmount' },
            { title: 'Claymore', href: '/sydney/claymore' },
            { title: 'Eagle Vale', href: '/sydney/eagle-vale' },
            { title: 'Eschol Park', href: '/sydney/eschol-park' },
            { title: 'Kearns', href: '/sydney/kearns' },
            { title: 'Raby', href: '/sydney/raby' },
            { title: 'St Andrews', href: '/sydney/st-andrews' },
            { title: 'Bardia', href: '/sydney/bardia' },
            { title: 'Macquire Links', href: '/sydney/macquire-links' },
            { title: 'Edmondson Park', href: '/sydney/edmondson-park' },
            { title: 'Prestons', href: '/sydney/prestons' },
            { title: 'Hoxton Park', href: '/sydney/hoxton-park' },
            { title: 'Horningsea Park', href: '/sydney/horningsea-park' },
            { title: 'Concord West', href: '/sydney/concord-west' },
            { title: 'Concord', href: '/sydney/concord' },
            { title: 'Burwood', href: '/sydney/burwood' },
            { title: 'Rodd Point', href: '/sydney/rood-point' },
            { title: 'Russell Lea', href: '/sydney/russell-lea' },
            { title: 'Brichgrove', href: '/sydney/brichgrove' },
            { title: 'Drummoyne', href: '/sydney/drummoyne' },
            { title: 'Wareemba', href: '/sydney/wareemba' },
            { title: 'Abbotsford', href: '/sydney/Abbotsford' },
            { title: 'Chiswick', href: '/sydney/Chiswick' },
            { title: 'Canada Bay', href: '/sydney/canada-bay' },
            { title: 'Strathfield', href: '/sydney/strathfield' },
            { title: 'North Strathfield', href: '/sydney/north-strathfield' },
            { title: 'Strathfield South', href: '/sydney/strathfield-south' },
            { title: 'Concord', href: '/sydney/concord' },
            { title: 'Cabarita', href: '/sydney/cabarita' },
            { title: 'Breakfast Point', href: '/sydney/breakfast-point' },
            { title: 'Mortlake', href: '/sydney/mortlake' },
            { title: 'Concord West', href: '/sydney/concord-west' },
            { title: 'Liberty Grove', href: '/sydney/liberty-grove' },
            { title: 'Rhodes', href: '/sydney/rhodes' },
            { title: 'Wentworth Point', href: '/sydney/wentworth' },
            {
                title: 'Sydney Olympic Park',
                href: '/sydney/sydney-olympic-park',
            },
            {
                title: 'Newington',
                href: '/sydney/newington',
            },
            {
                title: 'Silverwater',
                href: '/sydney/silverwater',
            },
            {
                title: 'Enfield',
                href: '/sydney/enfield',
            },
            {
                title: 'Burwood Heights',
                href: '/sydney/burwood-heights',
            },
            {
                title: 'Ashbury',
                href: '/sydney/ashbury',
            },
            { title: 'Croydon', href: '/sydney/croydon' },
            { title: 'Croydon Park', href: '/sydney/croydon-park' },
            { title: 'Ashbury', href: '/sydney/ashbury' },
            { title: 'Lewisham', href: '/sydney/lewisham' },
            { title: 'Homebush', href: '/sydney/homebush' },
            { title: 'Lidcome', href: '/sydney/lidcome' },
            { title: 'Greenwich', href: '/sydney/greenwich' },
            { title: 'Northwood', href: '/sydney/northwood' },
            { title: 'Cammeray', href: '/sydney/cammeray' },
            { title: 'Kurraba Point', href: '/sydney/kurraba-point' },
            { title: 'Cremorne Point', href: '/sydney/cremorne-point' },
            { title: 'Lane Cove', href: '/sydney/lane-cove' },
            { title: 'Longueville', href: '/sydney/longueville' },
            { title: 'Riverview', href: '/sydney/riverview' },
            { title: 'Linley Point', href: '/sydney/linley-point' },
            { title: 'Lane Cove West', href: '/sydney/lane-cove-west' },
            { title: 'Lane Cove North', href: '/sydney/lane-cove-north' },
            { title: 'Artarmon', href: '/sydney/artarmon' },
            { title: 'Castlecrag', href: '/sydney/castlecrag' },
            { title: 'Middle Cove', href: '/sydney/middle-cove' },
            { title: 'Castle Cove', href: '/sydney/castle-cove' },
            { title: 'Roseville Chase', href: '/sydney/roseville-chase' },
            { title: 'Chatswood West', href: '/sydney/chatswood-west' },
            { title: 'East Lindfield', href: '/sydney/east-lindfield' },
            { title: 'Killara', href: '/sydney/killara' },
            { title: 'East Killara', href: '/sydney/east-killara' },
            { title: 'Gordon', href: '/sydney/gordon' },
            { title: 'Pymble', href: '/sydney/pymble' },
            { title: 'West Pymble', href: '/sydney/west-pymble' },
            { title: 'Turramurra', href: '/sydney/turramurra' },
            { title: 'South Turramurra', href: '/sydney/south-turramurra' },
            { title: 'North Turramurra', href: '/sydney/north-turramurra' },
            { title: 'St. Leves', href: '/sydney/st-leves' },
            { title: 'St. Leves Chase', href: '/sydney/st-leves-chase' },
            { title: 'Warrawee', href: '/sydney/warrawee' },
            { title: 'Wahroonga', href: '/sydney/wahroonga' },
            { title: 'North Wahroonga', href: '/sydney/north-wahroonga' },
            { title: 'Waitara', href: '/sydney/waitara' },
            { title: 'Hornsby', href: '/sydney/hornsby' },
            { title: 'Asquith', href: '/sydney/asquith' },
            { title: 'Normanhurst', href: '/sydney/normanhurst' },
            { title: 'Thornleight', href: '/sydney/thornleigh' },
            { title: 'Westleigh', href: '/sydney/westleigh' },
            { title: 'Pennant Hills', href: '/sydney/pennant-hills' },
            { title: 'Beecroft', href: '/sydney/beecroft' },
            { title: 'Cheltenham', href: '/sydney/Cheltenham' },
            { title: 'Epping', href: '/sydney/epping' },
            { title: 'North Epping', href: '/sydney/north-epping' },
            { title: 'Eastwood', href: '/sydney/eastwood' },
            { title: 'Marsfield', href: '/sydney/marsfield' },
            { title: 'Maquire Park', href: '/sydney/maquire-park' },
            { title: 'Denistone', href: '/sydney/denistone' },
            { title: 'Denistone East', href: '/sydney/denistone-east' },
            { title: 'Denistone West', href: '/sydney/denistone-west' },
            { title: 'Meadowbank', href: '/sydney/meadowbank' },
            { title: 'Putney', href: '/sydney/putney' },
            { title: 'Tunnyson Point', href: '/sydney/tennyson-point' },
            { title: 'Gladsville', href: '/sydney/gladsville' },
            { title: 'Henley', href: '/sydney/henley' },
            { title: 'Huntleys Cove', href: '/sydney/huntleys-cove' },
            { title: 'Henley', href: '/sydney/henley' },
            { title: 'Huntleys Point', href: '/sydney/huntleys-point' },
            { title: 'Huntleys Cove', href: '/sydney/huntleys-cove' },
            { title: 'Hunters Hill', href: '/sydney/hunters-hill' },
            { title: 'Ryde', href: '/sydney/ryde' },
            { title: 'East Ryde', href: '/sydney/east-ryde' },
            { title: 'North Ryde', href: '/sydney/north-ryde' },
            { title: 'Macdonaldtown', href: '/sydney/macdonaldtown' },
            { title: 'Erskineville', href: '/sydney/erskineville' },
            { title: 'St Peters', href: '/sydney/st-peters' },
            { title: 'Sydenham', href: '/sydney/sydenham' },
            { title: 'Dover Heights', href: '/sydney/dover-heights' },
            { title: 'Watsons Bay', href: '/sydney/watsons-bay' },
            { title: 'Kings Cross', href: '/sydney/kings-cross' },
            { title: 'Woollahra', href: '/sydney/woollahra' },
            { title: 'Centennial Park', href: '/sydney/centennial-park' },
            { title: 'Queens Park', href: '/sydney/queens-park' },
            { title: 'Phillip Bay', href: '/sydney/phillip-bay' },
            { title: 'Eastgardens', href: '/sydney/eastgardens' },
            { title: 'Banksmeadow', href: '/sydney/banksmeadow' },
            { title: 'Hillsdale', href: '/sydney/hillsdale' },
            { title: 'Moore Park', href: '/sydney/moore-park' },
            { title: 'Enmore', href: '/sydney/enmore' },
            { title: 'Melrose Park', href: '/sydney/melrose-park' },
            { title: 'Ermington', href: '/sydney/ermington' },
            { title: 'Rydalmere', href: '/sydney/rydalmere' },
            { title: 'Rosehill', href: '/sydney/rosehill' },
            { title: 'Camellia', href: '/sydney/camellia' },
            { title: 'Clyde', href: '/sydney/clyde' },
            { title: 'Granville', href: '/sydney/granville' },
            { title: 'Harris Park', href: '/sydney/harris-park' },
            { title: 'North Parramatta', href: '/sydney/north-parramatta' },
            { title: 'Westmead', href: '/sydney/westmead' },
            { title: 'Dundas', href: '/sydney/dundas' },
            { title: 'Telopea', href: '/sydney/telopea' },
            { title: 'Dundas Valley', href: '/sydney/dundas-valley' },
            { title: 'Oatlands', href: '/sydney/oatlands' },
            { title: 'Carlingfords', href: '/sydney/carlingford' },
            { title: 'West Pennant Hills', href: '/sydney/west-pennant-hills' },
            { title: 'Pennant Hills', href: '/sydney/pennant-hills' },
            { title: 'Cherrybrook', href: '/sydney/cherrybrook' },
            { title: 'North Rocks', href: '/sydney/north-rocks' },
            { title: 'Northmead', href: '/sydney/northmead' },
            { title: 'Castle Hill', href: '/sydney/castle-hill' },
            { title: 'Baulkham Hills', href: '/sydney/baulkham-hills' },
            { title: 'Kellyville', href: '/sydney/kellyville' },
            { title: 'Norwest', href: '/sydney/norwest' },
            { title: 'Bella Vista', href: '/sydney/bella-vista' },
            { title: 'Quakers Hill', href: '/sydney/quakers-hill' },
            { title: 'Toongabbie', href: '/sydney/toongabbie' },
            { title: 'Balgowlah Heights', href: '/sydney/balgowlah-heights' },
            { title: 'Clontarf', href: '/sydney/clontarf' },
            { title: 'North Balgowlah', href: '/sydney/north-balgowlah' },
            { title: 'Manly Vale', href: '/sydney/manly-vale' },
            { title: 'Fairlight', href: '/sydney/fairlight' },
            { title: 'Queenscliff', href: '/sydney/queenscliff' },
            { title: 'Freshwater', href: '/sydney/freshwater' },
            { title: 'North Manly', href: '/sydney/north-manly' },
            { title: 'Brookvale', href: '/sydney/brookvale' },
            { title: 'North Curl Curl', href: '/sydney/north-curl-curl' },
            { title: 'Dee Why', href: '/sydney/dee-why' },
            { title: 'Narraweena', href: '/sydney/narraweena' },
            { title: 'Allambie Heights', href: '/sydney/allambie-heights' },
            { title: 'Beacon Hill', href: '/sydney/beacon-hill' },
            { title: 'Frenchs Forest', href: '/sydney/frenchs-forest' },
            { title: 'Cromer', href: '/sydney/cromer' },
        ],
    },
    {
        title: 'Melbourne',
        meta: {},
        items: [
            { title: 'Abbotsford', href: '/melbourne/abbotsford' },
            { title: 'Aberfeldie', href: '/melbourne/aberfeldie' },
            { title: 'Airport West', href: '/melbourne/airport-west' },
            { title: 'Ascot Vale', href: '/melbourne/ascot-vale' },
            { title: 'Ashburton', href: '/melbourne/ashburton' },
            { title: 'Ashwood', href: '/melbourne/ashwood' },
            { title: 'Aspendale', href: '/melbourne/aspendale' },
            { title: 'Avondale Heights', href: '/melbourne/avondale-heights' },
            { title: 'Balaclava', href: '/melbourne/balaclava' },
            { title: 'Balwyn', href: '/melbourne/balwyn' },
            { title: 'Bayswater', href: '/melbourne/bayswater' },
            { title: 'Beaconsfield', href: '/melbourne/beaconsfield' },
            { title: 'Beaumaris', href: '/melbourne/beaumaris' },
            { title: 'Bellfield', href: '/melbourne/bellfield' },
            { title: 'Bentleigh', href: '/melbourne/bentleigh' },
            { title: 'Blackburn', href: '/melbourne/blackburn' },
            { title: 'Black Rock', href: '/melbourne/black-rock' },
            { title: 'Box Hill', href: '/melbourne/box-hill' },
            { title: 'Brighton', href: '/melbourne/brighton' },
            { title: 'Clifton Hill', href: '/melbourne/clifton-hill' },
            { title: 'Coburg', href: '/melbourne/coburg' },
            { title: 'Collingwood', href: '/melbourne/collingwood' },
            { title: 'Craigieburn', href: '/melbourne/craigieburn' },
            { title: 'Cranbourne', href: '/melbourne/cranbourne' },
            { title: 'Cremorne', href: '/melbourne/cremorne' },
            { title: 'Croydon', href: '/melbourne/croydon' },
            { title: 'Dandenong', href: '/melbourne/dandenong' },
            { title: 'Diamond Creek', href: '/melbourne/diamond-creek' },
            { title: 'Doncaster', href: '/melbourne/doncaster' },
            { title: 'Eaglemont', href: '/melbourne/eaglemont' },
            { title: 'East Melbourne', href: '/melbourne/east-melbourne' },
            { title: 'Elsternwick', href: '/melbourne/elsternwick' },
            { title: 'Eltham', href: '/melbourne/eltham' },
            { title: 'Elwood', href: '/melbourne/elwood' },
        ],
    },
];
