export const cities = [
    {
        title: 'Sydney',
        items: [
            { title: 'Newtown', href: '/' },
            { title: 'Redfern', href: '/' },
            { title: 'Surry Hills', href: '/' },
            { title: 'Ultimo', href: '/' },
            { title: 'Alexandria', href: '/' },
            { title: 'Waterloo', href: '/' },
            { title: 'Petersham', href: '/' },
            { title: 'Summer Hill', href: '/' },
            { title: 'Dulwich Hill', href: '/' },
            { title: 'Leichhardt', href: '/' },
            { title: 'Annadale', href: '/' },
            { title: 'Glebe', href: '/' },
            { title: 'Eveleigh', href: '/' },
            { title: 'Rosebery', href: '/' },
            { title: 'Zetland', href: '/' },
            { title: 'Mascot', href: '/' },
            { title: 'Kensington', href: '/' },
            { title: 'Darlinghurst', href: '/' },
            { title: 'Marrickville', href: '/' },
            { title: 'Potts Point', href: '/' },
            { title: 'Bondi Junction', href: '/' },
            { title: 'Coogee', href: '/' },
            { title: 'South Coogee', href: '/' },
            { title: 'Bondi', href: '/' },
            { title: 'Little Bay', href: '/' },
            { title: 'Malabar', href: '/' },
            { title: 'Malabar', href: '/' },
            { title: 'Bronte', href: '/' },
            { title: 'Clovelly', href: '/' },
            { title: 'Waverley', href: '/' },
            { title: 'Randwick', href: '/' },
            { title: 'Kingsford', href: '/' },
            { title: 'Rose Bay', href: '/' },
            { title: 'Double Bay', href: '/' },
            { title: 'Maroubra', href: '/' },
            { title: 'Malabar', href: '/' },
            { title: 'Chifley', href: '/' },
            { title: 'Ramsgate', href: '/' },
            { title: 'Rockdale', href: '/' },
            { title: 'Chatswood', href: '/' },
            { title: 'Neutral Bay', href: '/' },
            { title: 'North Sydney', href: '/' },
            { title: 'Cammeryay', href: '/' },
            { title: 'Crows Nest', href: '/' },
            { title: 'St Leonards', href: '/' },
            { title: 'Mosman', href: '/' },
        ],
    },
];
